name: Auto Rebase Develop

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  rebase-develop:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch develop branch
        run: |
          git fetch origin develop
          git checkout develop

      - name: Rebase develop onto main
        id: rebase
        run: |
          set +e
          git rebase origin/main
          echo "REBASE_EXIT_CODE=$?" >> $GITHUB_ENV
          set -e

      - name: Push changes if rebase successful
        if: env.REBASE_EXIT_CODE == '0'
        run: |
          git push origin develop

      - name: Get PR creator
        if: env.REBASE_EXIT_CODE != '0'
        id: pr_creator
        run: |
          echo "pr_creator=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT

      - name: Read Slack map JSON
        if: env.REBASE_EXIT_CODE != '0'
        id: read_slack_map
        run: |
          echo "map=$(cat .github/slack-map.json | jq -c .)" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        if: env.REBASE_EXIT_CODE != '0'
        uses: slackapi/slack-github-action@v2.1.0
        with:
          payload: |
            🚨 *Conflict Alert!*
            👤 <@${{ fromJson(steps.read_slack_map.outputs.map)[steps.pr_creator.outputs.pr_creator] }}>, your PR to *main* caused a conflict with *develop*.
            ⚡ *Action needed*: Please resolve it ASAP! 🚀
            🔗 *PR link*: <${{ github.event.pull_request.html_url }}|Click here to view your PR>

            👉 *How to fix it:*
            • Checkout `develop`, pull latest
            • Create branch `resolve-conflict`
            • Merge `main` into it
            • Resolve conflicts, commit, push
            • Open PR from `resolve-conflict` to `develop`
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

