name: Auto Rebase Develop

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  rebase-develop:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch develop branch
        run: |
          git fetch origin develop
          git checkout develop

      - name: Rebase develop onto main
        id: rebase
        run: |
          set +e
          git rebase origin/main
          echo "REBASE_EXIT_CODE=$?" >> $GITHUB_ENV
          set -e

      - name: Push changes if rebase successful
        if: env.REBASE_EXIT_CODE == '0'
        run: |
          git push origin develop

      - name: Get PR creator
        if: env.REBASE_EXIT_CODE != '0'
        id: pr_creator
        run: |
          echo "pr_creator=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT

      - name: Read Slack map JSON
        if: env.REBASE_EXIT_CODE != '0'
        id: read_slack_map
        run: |
          echo "map=$(cat .github/slack-map.json | jq -c .)" >> $GITHUB_OUTPUT

      - name: Send main Slack notification
        if: env.REBASE_EXIT_CODE != '0'
        id: slack_main
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":warning: Conflict detected when rebasing develop onto main!\n<@${{ fromJson(steps.read_slack_map.outputs.map)[steps.pr_creator.outputs.pr_creator] }}>, you just merged a PR into *main* that caused a conflict with *develop*.",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚨 Conflict Detected: develop vs main!",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<@${{ fromJson(steps.read_slack_map.outputs.map)[steps.pr_creator.outputs.pr_creator] }}>, you just merged a PR into *main* that caused a conflict with *develop* :warning:"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send guide as thread reply
        if: env.REBASE_EXIT_CODE != '0'
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "How to resolve conflict (steps below) :hammer_and_wrench:",
              "thread_ts": "${{ steps.slack_main.outputs.ts }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*:hammer_and_wrench: What to do next:*\n\n:one: *Checkout develop and pull latest*\n```git checkout develop && git pull origin develop```\n:two: *Create a temp branch*\n```git checkout -b resolve-conflict```\n:three: *Merge main into this branch*\n```git merge origin/main```\n:four: *Resolve conflicts, commit & push*\n```git add .\ngit commit -m \"Resolve conflict: merge main into develop\"\ngit push origin resolve-conflict```\n:five: *Open a PR from `resolve-conflict` to `develop`*\n\n:tada: *Once merged, auto-rebase will work again!* :rocket:"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
